comp_i2cmb_env_pkg:
	vlog $(ECE745_PROJECT_HOME)/verification_ip/ncsu_pkg/ncsu_macros.svh
	vlog $(ECE745_PROJECT_HOME)/verification_ip/ncsu_pkg/ncsu_pkg.sv
	vlog $(ECE745_PROJECT_HOME)/verification_ip/environment_packages/i2cmb_env_pkg/i2cmb_env_pkg.sv
